services:
  - type: web
    name: spotify-checker-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium
      python -m playwright install-deps chromium
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: API_KEY
        value: sk_live_abc123xyz7898724352678
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
